apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app-deploy
  labels:
    app: healthcare-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: healthcare-app-container
        image: chandan3461/healthcare_app_img:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-app-service
spec:
  selector:
    app: healthcare-app
  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8082
